# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9fdfe2fb036078fdccf43bae5baeab0fa32988ace0f3b483169d87aa139bb7832988021a26df2800f33813e66bf298f16ea8be8d672e01baf2625449cece03eb

test:
  secret_key_base: 618fce050403c87ac1ac03fa81344ffe93f3bd3f1a50a93546af41c9badf1ffb39a40d21565cb53e4f2782a0e5e8f177b422e8fd0b3f25e8c7375e531fa843e0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
